/**
 * Copyright 2026 Huawei Technologies Co., Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef MUSE_DIALECT_MUSE_OPS_DIALECT_H
#define MUSE_DIALECT_MUSE_OPS_DIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Types.h"

// Include the generated dialect header
#include "mfusion/Dialect/Muse/MuseDialect.h.inc"

namespace mlir {
namespace muse {

// Additional dialect methods can be added here if needed
// The main dialect class is generated by TableGen

}  // namespace muse
}  // namespace mlir

#endif  // MUSE_DIALECT_MUSE_OPS_DIALECT_H
