# Copyright 2025 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from typing import Any, Coroutine, Optional, Protocol

from .intents import UIIntent
from .state import InfoPanelState, WorkflowPanelState
from .types import MainContent


class LayoutManager(Protocol):
    """UI 布局管理器抽象（Presenter 只依赖该接口）。"""

    def run(self, workflow_task: Coroutine[Any, Any, Any]) -> None: ...
    def stop(self) -> None: ...
    def is_ui_active(self) -> bool: ...

    def update_main_content(self, content: MainContent) -> None: ...

    def update_info_state(self, state: InfoPanelState) -> None: ...
    def patch_info_state(self, **kwargs: Any) -> None: ...
    def update_workflow_state(self, state: WorkflowPanelState) -> None: ...
    def patch_workflow_state(self, **kwargs: Any) -> None: ...

    def append_trace_item(
        self, text: str, *, task_id: str, event_idx: int = 0
    ) -> None: ...
    def clear_trace(self) -> None: ...
    def set_trace_title(self, title: str) -> None: ...
    def set_trace_items(self, items: list[tuple[str, str, int]]) -> None: ...

    def set_task_tabs(
        self, items: list[tuple[str, str]], active_task_id: str = ""
    ) -> None: ...
    def set_active_task_tab(self, task_id: str) -> None: ...
    def reset_task_tabs(
        self, items: list[tuple[str, str]], active_task_id: str = ""
    ) -> None: ...
    def set_main_task_id(self, task_id: str) -> None: ...
    def get_main_task_id(self) -> str: ...
    def get_active_task_id(self) -> str: ...
    def is_on_main_tab(self) -> bool: ...

    def set_input_enabled(self, enabled: bool) -> None: ...
    async def await_user_input(self, prompt: str) -> str: ...

    def clear_log(self) -> None: ...
    def focus_chat(self) -> None: ...
    def focus_input(self) -> None: ...
    def focus_trace(self) -> None: ...

    def get_panel_content_width(self, panel: str = "chat") -> Optional[int]: ...

    def drain_ui_intents(self) -> list[UIIntent]: ...
