# 模型预设配置
agent_model_config:
  aul_designer: vllm_deepseek_r1_default
  aul_designer_fix: vllm_deepseek_r1_default
  swft_coder: vllm_deepseek_r1_default
  swft_coder_api: vllm_deepseek_r1_default
  swft_coder_fix: vllm_deepseek_r1_default
  triton_coder: vllm_deepseek_r1_default
  triton_coder_fix: vllm_deepseek_r1_default
  conductor_check: vllm_deepseek_r1_default
  conductor_analyze: vllm_deepseek_r1_default

# 日志配置
log_dir: "~/aikg_logs"