# 嵌入模型配置
embedding_model: "GanymedeNil/text2vec-large-chinese"  # 适用于中文特征描述
# 可选英文模型: "sentence-transformers/all-MiniLM-L6-v2"

# 向量数据库配置
distance_strategy: "COSINE"
verify_distance_strategy: "EUCLIDEAN_DISTANCE"

# 特征提取模型预设配置
agent_model_config:
  feature_extraction: deepseek_r1_default